version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 9017:27017 # 컨테이너 외부 : 컨테이너 내부
    environment:
      MONGO_INITDB_ROOT_USERNAME : root
      MONGO_INITDB_ROOT_PASSWORD : root_mongo
#    volumes:
#    - /Users/parkjieun/zeun_pjt/cdc_to_mongo/mongo/mongod.conf:/etc/mongod.conf
#    command:
#      - --config /etc/mongod.conf
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9018:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME : root
      ME_CONFIG_MONGODB_ADMINPASSWORD : root_mongo
      ME_CONFIG_MONGODB_SERVER : mongodb
    depends_on:
      - mongodb
  mysql:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_user
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci