version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 9017:27017 # 컨테이너 외부 : 컨테이너 내부
    environment:
      MONGO_INITDB_ROOT_USERNAME : root
      MONGO_INITDB_ROOT_PASSWORD : root_mongo
#    volumes:
#    - /Users/parkjieun/zeun_pjt/cdc_to_mongo/mongo/mongod.conf:/etc/mongod.conf
#    command:
#      - --config /etc/mongod.conf
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9018:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME : root
      ME_CONFIG_MONGODB_ADMINPASSWORD : root_mongo
      ME_CONFIG_MONGODB_SERVER : mongodb
    depends_on:
      - mongodb
  mysql:
    image: debezium/example-mysql # mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_mysql
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
  connect:
    image: debezium/connect
    depends_on:
      - kafka
    ports:
    - 8083:8083
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
    links:
      - zookeeper
      - kafka
      - mysql
